version: "2"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
    environment: 
      RABBITMQ_DEFAULT_VHOST: rabbit
