---
apiVersion: v1
kind: Namespace
metadata: 
  name: squidgame

#################Dummy Deployment/Service#####################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo-deployment
  labels:
    app: go-hello
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
      annotations:
        linkerd.io/inject: enabled        
    spec:
      containers:
      - name: hellogo-container
        image: ldecast/sopes1:api_v0

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-hello
  name: go-service
  namespace: squidgame
spec:
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: go-hello
  type: ClusterIP


################################### CLIENTE/SERVER  #####################################
######### PUBSUB #########
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-deployment
  labels:
    app: pubsub
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pubsub
  template:
    metadata:
      labels:
        app: pubsub
      annotations:
        linkerd.io/inject: enabled        
    spec:
      containers:
      - name: pubsub-client
        image: ldecast/sopes1:client_pubsub
      - name: pubsub-server
        image: ldecast/sopes1:server_pubsub
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pubsub
  name: pubsub-service
  namespace: squidgame
spec:
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: pubsub
  type: ClusterIP



---
######### RABBIT MQ #########
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        linkerd.io/inject: enabled        
    spec:
      containers:
      - name: rabbitmq-endpoint
        image: rabbitmq:3-management  
        ports:
        - containerPort: 5672
      - name: rabbitmq-client
        image: ldecast/sopes1:client_rabbitmq
      - name: rabbitmq-server
        image: ldecast/sopes1:server_rabbitmq_v1        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-service
  namespace: squidgame
spec:
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: rabbitmq
  type: ClusterIP
#RABBITMQ service to expose port to worker 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-sw-service
  namespace: squidgame
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP
---

######### KAFKA #########
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        linkerd.io/inject: enabled        
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper 
        ports:
        - containerPort: 2181
      - name: kafka-container
        image: wurstmeister/kafka 
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "localhost:2181"
      - name: kafka-client
        image: ldecast/sopes1:client_kafka_v1
        ports:
        - containerPort: 10000
      - name: kafka-server
        image: ldecast/sopes1:server_kafka_v1
      - name: kafka-worker-container
        image: ldecast/sopes1:worker_kafka_v3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
  namespace: squidgame
spec:
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: kafka
  type: ClusterIP
#RABBITMQ service to expose port to worker 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-sw-service
  namespace: squidgame
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP
---





###############################################WORKERS ############################################
#PUBSUB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-w-deployment
  labels:
    app: pubsub-w
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pubsub-w
  template:
    metadata:
      labels:
        app: pubsub-w     
    spec:
      containers:
      - name: pubsub-worker
        image: ldecast/sopes1:worker_pubsub
---
##### RABBITMQ WORKER#######
#RABBITMQ WORKER CONGIF MAP
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-w-configmap
  namespace: squidgame
data:
  rabbitmq-url: rabbitmq-sw-service #is the name of the DB server or it could be the name of the service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-w-deployment
  labels:
    app: rabbitmq-w
  namespace: squidgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq-w
  template:
    metadata:
      labels:
        app: rabbitmq-w       
    spec:
      containers:
      - name: rabbitmq-worker
        image: ldecast/sopes1:worker_rabbitmq
        env:
        - name: rabbitmq_address
          valueFrom: 
            configMapKeyRef:
              name: rabbitmq-w-configmap   #configmap name
              key: rabbitmq-url         #the name of the key in the config map




######################## INGRESS #################################
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/service-upstream: "true"
  name: svc-ingress-1
  namespace: squidgame
spec: 
  rules: 
    - 
      host: 35.188.110.226.nip.io
      http: 
        paths: 
          - 
            backend: 
              service:
                name: pubsub-service
                port: 
                  number: 10000
            path: /pubsub
            pathType: Prefix
          - 
            backend: 
              service:
                name: rabbitmq-service
                port: 
                  number: 10000
            path: /rabbit
            pathType: Prefix
          - 
            backend: 
              service:
                name: kafka-service
                port: 
                  number: 10000
            path: /kafka
            pathType: Prefix
          - 
            backend: 
              service:
                name: go-service
                port: 
                  number: 10000
            path: /
            pathType: Prefix
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/service-upstream: "true"
  name: svc-ingress-2
  namespace: squidgame
spec: 
  rules: 
    - 
      host: sopes1usac2s.com 
      http: 
        paths: 
          - 
            backend: 
              service:
                name: pubsub-service
                port: 
                  number: 10000
            path: /pubsub
            pathType: Prefix
          - 
            backend: 
              service:
                name: rabbitmq-service
                port: 
                  number: 10000
            path: /rabbit
            pathType: Prefix
          - 
            backend: 
              service:
                name: kafka-service
                port: 
                  number: 10000
            path: /kafka
            pathType: Prefix
          - 
            backend: 
              service:
                name: go-service   ######### TODO
                port: 
                  number: 10000
            path: /
            pathType: Prefix



######################## LINKERD ############################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: error-injector
  namespace: squidgame
data:
 nginx.conf: |-
    events {}
    http {
        server {
          listen 10000;
            location / {
                return 500;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-injector
  namespace: squidgame
  labels:
    app: error-injector
spec:
  selector:
    matchLabels:
      app: error-injector
  replicas: 1
  template:
    metadata:
      labels:
        app: error-injector
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: error-injector
---
apiVersion: v1
kind: Service
metadata:
  name: error-injector
  namespace: squidgame
spec:
  ports:
  - name: service
    port: 10000 
  selector:
    app: error-injector

---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: error-split
  namespace: squidgame
spec:
  service: go-service
  backends:
  - service: pubsub-service
    weight: 250m
  - service: rabbitmq-service
    weight: 250m
  - service: kafka-service
    weight: 250m  
  - service: error-injector
    weight: 250m

---
